[theme]
# Primary accent color for interactive elements
primaryColor = "#FF4B4B"

# Background color for the main content area
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#262730"

# Color used for almost all text
textColor = "#F0F2F6"

# Font family for all text in the app
font = "monospace"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false